name: Web App CI Workflow

on: [push, pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5434:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
    
      - name: Install dependencies for Web App
        working-directory: ./apps/web_app
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          poetry lock --no-update
          poetry install
    
      - name: Run Tests for Web App
        working-directory: ./apps/web_app
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          cp .env.example .env
          poetry run pytest
     
      - name: Install dependencies for Shared
        working-directory: ./apps/shared
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          poetry lock --no-update
          poetry install
    
      - name: Run Tests for Shared
        working-directory: ./apps/shared
        run: |
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          poetry run pytest
